resources:
  - name: dwpdigital-dataworks-sft-ingress-agent
    type: registry-image-resource
    source:
      repository: dwpdigital/dataworks-sft-ingress-agent
    check_every: 5m

  - name: ecr-dwpdigital-dataworks-sft-ingress-agent-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "dataworks-sft-ingress-agent"

  - name: ecr-dwpdigital-dataworks-sft-ingress-agent
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "dataworks-sft-ingress-agent"
      aws_role_arn: arn:aws:iam::((aws_account.management)):role/ci

jobs:
  - name: mirror-dwpdigital-dataworks-sft-ingress-agent-dev
    serial_groups: [dataworks-sft-ingress-agent]
    plan:
      - get: dwpdigital-dataworks-sft-ingress-agent
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-dataworks-sft-ingress-agent-dev
        params:
          image: "dwpdigital-dataworks-sft-ingress-agent/image.tar"
        attempts: 3

  - name: mirror-dwpdigital-dataworks-sft-ingress-agent
    serial_groups: [dataworks-sft-ingress-agent]
    plan:
      - get: dwpdigital-dataworks-sft-ingress-agent
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-dataworks-sft-ingress-agent
        params:
          image: "dwpdigital-dataworks-sft-ingress-agent/image.tar"
        attempts: 3
